spring:
  application:
    name: @artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/scaffold?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jason.@artifactId@.entity
  type-enums-package: com.jason.@artifactId@.enums
  configuration:
    cache-enabled: false
logging:
  level:
    com:
      jason:
        scaffold:
          mapper: debug
server:
  port: 3737